---
title: "Option_price"
author: "Shiyuan Wang"
date: "6/1/2021"
output: pdf_document
---

```{r, echo = TRUE}
#LIBRARIES
library(keras)
library(tensorflow)
library(tidyr)
library(RSQLite)
library(tibble)
library(data.table)
library(dplyr)
library(lubridate)
library(zoo)
```


```{r echo = TRUE , message=FALSE, warning=FALSE}
###Hyperparameters
n_units = 400
layers = 4
n_batch = 1024
n_epochs = 200
df <- read.csv("D:/desktop/Option_price/daily-closing-prices.csv")
estimate_sigma <- function(a){
  sd(diff(a, lag = 1)/a)
}
df$sigma_20[20:nrow(df)] <- rollapply(df$close, width = 20, FUN = estimate_sigma)
df <- df[,-2]
df$date <- ymd(df$date)
df$date <- format(df$date, format = "%Y/%m/%d")
dcon <- dbConnect(SQLite(), dbname = "option_price.db")
options_df <- dbGetQuery(conn = dcon, "
SELECT secid, date, symbol, exdate, strike_price, best_bid, best_offer, volume, open_interest, impl_volatility, cp_flag
FROM option_price;
")
options_df <- options_df[-1,]
options_df <- options_df[,-c(4,10)]
row.names(options_df) <- NULL
options_df_with_sigma <- left_join(options_df, df)
options_df_with_sigma
options_df_new <- drop_na(options_df_with_sigma)
options_df_new_put <- options_df_new[options_df_new$cp_flag == "P",]
options_df_new_call <- options_df_new[options_df_new$cp_flag == "C",]
options_df_new_put <- options_df_new_put[,-9]
options_df_new_call <- options_df_new_call[,-9]
```

```{r, echo = TRUE}
###Functions
black_scholes_put <- function(row){
    S = row$closing_price
    X = row$strike_price / 1000
    T = row$date_ndiff / 365
    r = row$treasury_rate / 100
    σ = row$sigma_20
    d1 = (np.log(S / X) + (r + (σ ^ 2) / 2) * T) / (σ * (T ^ 0.5))
    d2 = d1 - σ * (T ^ 0.5)
    P  = qnorm(-d2) * X * np.exp(-r * T) - S * norm.cdf(-d1)
    return(P)
}

black_scholes <- function(row){
    S = row$closing_price
    X = row$strike_price / 1000
    T = row$date_ndiff / 365
    r = row$treasury_rate / 100
    σ = row$sigma_20
    d1 = (np.log(S / X) + (r + (σ ^ 2) / 2) * T) / (σ * (T ^ 0.5))
    d2 = d1 - σ * (T ^ 0.5)
    C = S * qnorm(d1) - X * np.exp(-r * T) * norm.cdf(d2)
    return(C) 
}

###Function for calculating date difference 
date_diff <- function(row){
  date_dif <- c()
  for (i in 1:nrow(row)){
    start = toString(options[i,]["date"])
    end = toString(options[i,]["exdate"])
    start.1 = unlist(strsplit(start, "/"))
    s_year = start.1[1]
    s_month = start.1[2]
    s_day = start.1[3]
    end.1 = unlist(strsplit(end, "/"))
    e_year = end.1[1]
    e_month = end.1[2]
    e_day = end.1[3]
    start_time <- as.integer(paste0(s_year, s_month, s_day)) %>% 
      lubridate::ymd() %>% format("%Y/%m/%d")
    end_time <- as.integer(paste0(e_year, e_month, e_day)) %>% 
      lubridate::ymd() %>% format("%Y/%m/%d")
    date_dif[i] <- as.numeric(difftime(end_time, start_time, units = "auto"))
  }
  return(date_dif)
}



```

```{r echo = FALSE, message=FALSE, warning=FALSE}
###Data preprocess
options <- dbGetQuery(conn = dcon, "
SELECT secid, date, symbol, exdate, strike_price, best_bid, best_offer, volume, open_interest, impl_volatility, cp_flag
FROM option_price;
")

###Do not run this code unless you really want to see the result, it will take forever
options$date_ndiff <- date_diff(options)

```

```{r, echo = TRUE}
###Data cleaning for treasury rate






```
